#include <input/Input.hpp>

#include <map>
#include <string>

using namespace sr::input;

namespace
{
GamepadStateTracker  g_GamePadStateTrackers[Gamepad::MAX_PLAYERS];
KeyboardStateTracker g_KeyboardStateTracker;
MouseStateTracker    g_MouseStateTracker;

std::map<std::string, SDL_Scancode> g_KeyMap = {
    { "a", SDL_SCANCODE_A },
    { "b", SDL_SCANCODE_B },
    { "c", SDL_SCANCODE_C },
    { "d", SDL_SCANCODE_D },
    { "e", SDL_SCANCODE_E },
    { "f", SDL_SCANCODE_F },
    { "g", SDL_SCANCODE_G },
    { "h", SDL_SCANCODE_H },
    { "i", SDL_SCANCODE_I },
    { "j", SDL_SCANCODE_J },
    { "k", SDL_SCANCODE_K },
    { "l", SDL_SCANCODE_L },
    { "m", SDL_SCANCODE_M },
    { "n", SDL_SCANCODE_N },
    { "o", SDL_SCANCODE_O },
    { "p", SDL_SCANCODE_P },
    { "q", SDL_SCANCODE_Q },
    { "r", SDL_SCANCODE_R },
    { "s", SDL_SCANCODE_S },
    { "t", SDL_SCANCODE_T },
    { "u", SDL_SCANCODE_U },
    { "v", SDL_SCANCODE_V },
    { "w", SDL_SCANCODE_W },
    { "x", SDL_SCANCODE_X },
    { "y", SDL_SCANCODE_Y },
    { "z", SDL_SCANCODE_Z },
    { "1", SDL_SCANCODE_1 },
    { "2", SDL_SCANCODE_2 },
    { "3", SDL_SCANCODE_3 },
    { "4", SDL_SCANCODE_4 },
    { "5", SDL_SCANCODE_5 },
    { "6", SDL_SCANCODE_6 },
    { "7", SDL_SCANCODE_7 },
    { "8", SDL_SCANCODE_8 },
    { "9", SDL_SCANCODE_9 },
    { "0", SDL_SCANCODE_0 },
    { "up", SDL_SCANCODE_UP },
    { "down", SDL_SCANCODE_DOWN },
    { "left", SDL_SCANCODE_LEFT },
    { "right", SDL_SCANCODE_RIGHT },
    { "[1]", SDL_SCANCODE_KP_1 },
    { "[2]", SDL_SCANCODE_KP_2 },
    { "[3]", SDL_SCANCODE_KP_3 },
    { "[4]", SDL_SCANCODE_KP_4 },
    { "[5]", SDL_SCANCODE_KP_5 },
    { "[6]", SDL_SCANCODE_KP_6 },
    { "[7]", SDL_SCANCODE_KP_7 },
    { "[8]", SDL_SCANCODE_KP_8 },
    { "[9]", SDL_SCANCODE_KP_9 },
    { "[0]", SDL_SCANCODE_KP_0 },
    { "[+]", SDL_SCANCODE_KP_PLUS },
    { "[-]", SDL_SCANCODE_KP_MINUS },
    { "[*]", KeyCode::Multiply },
    { "[=]", KeyCode::Separator },  // TODO: Which is the [=] key on the numpad?
    { "[/]", KeyCode::Divide },
    { "shift", KeyCode::ShiftKey },
    { "left shift", KeyCode::LeftShift },
    { "right shift", KeyCode::RightShift },
    { "ctrl", KeyCode::ControlKey },
    { "left ctrl", KeyCode::LeftControl },
    { "right ctrl", KeyCode::RightControl },
    { "alt", KeyCode::AltKey },
    { "left alt", KeyCode::LeftAlt },
    { "right alt", KeyCode::RightAlt },
    { "left win", KeyCode::LeftWindows },
    { "right win", KeyCode::RightWindows },
    { "backspace", KeyCode::Back },
    { "tab", KeyCode::Tab },
    { "enter", KeyCode::Enter },
    { "return", KeyCode::Enter },
    { "esc", KeyCode::Escape },
    { "escape", KeyCode::Escape },
    { "space", KeyCode::Space },
    { "delete", KeyCode::Delete },
    { "ins", KeyCode::Insert },
    { "insert", KeyCode::Insert },
    { "home", KeyCode::Home },
    { "end", KeyCode::End },
    { "pgup", KeyCode::PageUp },
    { "page up", KeyCode::PageUp },
    { "pgdn", KeyCode::PageDown },
    { "page down", KeyCode::PageDown },
    { "F1", SDL_SCANCODE_F1 },
    { "F2", SDL_SCANCODE_F2 },
    { "F3", SDL_SCANCODE_F3 },
    { "F4", SDL_SCANCODE_F4 },
    { "F5", SDL_SCANCODE_F5 },
    { "F6", SDL_SCANCODE_F6 },
    { "F7", SDL_SCANCODE_F7 },
    { "F8", SDL_SCANCODE_F8 },
    { "F9", SDL_SCANCODE_F9 },
    { "F10", SDL_SCANCODE_F10 },
    { "F11", SDL_SCANCODE_F11 },
    { "F12", SDL_SCANCODE_F12 },
};
}  // namespace